#!/usr/bin/env python3
from factorio_blueprint_analyser import (
    options,
    blueprint_analyser
)

import json

if __name__ == "__main__":
    # Read and check the user parameters
    options.read_options()

    blueprint_analyser.init()

    analysed_blueprint = blueprint_analyser.analyse_blueprint_from_path(
        options.input)

    # Export analysed blueprint in a json file
    with open(options.output, "w") as f:
        f.write(json.dumps(analysed_blueprint, indent=4))
